SELECT * FROM proyecto.presentations;



INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('The next Outbreak','2015-3-9','TED','Vancouver','Sustainability','English','2018-11-21 08:49:31', '2019-11-15 14:33:54', 'https://www.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare', 2);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Do schools kill creativity?','2006-2-28','TED','Monterrey','Social','English','2019-06-28 20:16:46', '2020-04-03 18:15:10', 'https://www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare',  3);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('My stroke of inside','2008-2-13','TED','Monterrey','Science','English','2020-05-01 22:23:38', '2020-02-24 22:05:37', 'https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare', 2);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('The surprising science of hapiness','2004-2-7','TED','Monterrey','Science','English', '2019-06-16 17:05:42', '2020-04-08 22:03:57', 'https://www.ted.com/talks/dan_gilbert_the_surprising_science_of_happiness?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare', 3);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Why We Have Too Few Women Leaders','2010-12-1','TED','Washington DC','Feminism','English','2018-06-13 04:04:42', '2019-11-22 09:30:17', 'https://www.ted.com/talks/sheryl_sandberg_why_we_have_too_few_women_leaders?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare',  2);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Where does creativity hide?','2008-2-27','TED','Monterrey','Culture','English','2017-11-28 10:41:46', '2020-01-14 11:57:56', 'https://www.ted.com/talks/amy_tan_where_does_creativity_hide?utm_campaign=tedspread&utm_medium=referral&utm_source=tedcomshare',  2s);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Wireless Networks','2019-7-4','WCE','London','Technology','English','2018-02-21 20:31:38', '2019-10-28 15:05:31', 'ted.com/volutpat/erat/quisque/erat.html', 8);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('El Bulli','2010-1-27','Madrid Fusion','Madrid','Gastronomy','Spanish', '2020-02-22 13:39:34', '2020-04-11 00:37:40', 'globo.com/in/purus/eu/magna.png',  31);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Tesla S Presentation','2011-11-1','null','Fremont','Motoring','English','2019-04-24 23:20:51', '2020-01-11 02:35:58', 'nsw.gov.au/donec/ut.jpg',  44);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Introducing Macintosh','1984-1-24','null','San Francisco','Technology','English','2019-03-01 21:33:44', '2020-03-28 09:35:18', 'ebay.co.uk/magna/vestibulum.js', 26);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Introducing Windows 95','1995-8-24','null','Redmond','Technology','English','2019-10-19 08:47:15', '2020-05-01 14:49:06', 'surveymonkey.com/pellentesque/ultrices/mattis/odio.json',  10);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Join me in my climate strike','2019-9-21','UN Climate Action Summit','New York','Sustainability','English','2019-08-31 03:59:05', '2020-05-01 19:54:46', 'phpbb.com/adipiscing/elit/proin/risus.js',  47);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Water:Charity','2012-2-13','LeWeb','Paris','Sustainability','English','2019-09-04 21:46:22', '2020-04-05 00:34:55', 'nhs.uk/posuere.json', 2);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Computational Statistics and Data Engineering','2019-7-3','WCE','London','Technology','English','2017-08-24 13:06:04', '2019-10-16 19:43:49', 'fc2.com/augue/vestibulum/ante/ipsum/primis.aspx',  11);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Lack of trust','2019-10-4','FIATAWC','Capetown','Transport','English','2018-10-11 22:42:45', '2020-03-26 03:36:51', 'linkedin.com/augue/vel.html',38);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Human, Non-Human, Post-Human','2018-8-13','WCPhilosophy','Beijin','Social','English','2020-02-23 20:08:53', '2020-02-20 02:55:38', 'jalbum.net/condimentum/neque/sapien/placerat/ante/nulla.xml',  18);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Las algas,nuevas hortalizas del mar','2007-1-16','Madrid Fusion','Madrid','Gastronomy','Spanish','2018-08-17 17:46:41', '2019-10-02 09:27:19', 'usgs.gov/vel/pede/morbi.xml',  18);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Financial Engineering','2019-7-3','WCE','London','Technology','English','2018-07-18 09:18:47', '2019-11-03 00:55:10', 'nymag.com/non/mauris/morbi/non.js',  22);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Toward future railway service','2019-11-1','WCRR','Tokyo','Motoring','Japanese','2019-11-22 16:08:50', '2020-01-22 13:40:49', 'microsoft.com/vestibulum/sit/amet.jpg', 36);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Expressibility, Dialogue, Translatability','2018-8-20','WCPhilosophy','Beijin','Social','Chinese','2019-03-28 07:28:34', '2020-01-02 11:29:43', 'mozilla.org/in/hac/habitasse/platea/dictumst/etiam.js',2);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('The danger of a single history','2009-7-16','TED','London','Social','English','2020-04-09 07:53:51', '2020-01-22 10:18:54', 'salon.com/sociis/natoque/penatibus.png', 7);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Forefront logistic','2019-9-30','FIATAWC','Capetown','Transport','Arabian','2017-12-18 16:00:55', '2020-03-04 03:11:19', 'yellowpages.com/quis/lectus/suspendisse/potenti.aspx', 3);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('An Inconvenient Truth','2006-5-24','null','New York','Sustainability','English','2017-10-28 07:06:32', '2020-03-25 06:31:12', 'icio.us/at/vulputate/vitae/nisl/aenean/lectus/pellentesque.html', 18);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Postres de diseño','2005-1-20','Madrid Fusion','Madrid','Gastronomy','Spanish','2019-07-29 17:54:35', '2020-04-20 08:15:02', 'nymag.com/ante/nulla/justo/aliquam/quis/turpis.jsp', 38);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Mind, Brain, Body, Consciousness, Emotions','2018-8-13','WCPhilosophy','Beijin','Social','English','2020-04-29 13:49:55', '2020-02-25 14:12:52', 'taobao.com/convallis/nunc/proin/at/turpis/a/pede.html',  14);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Rolling Stock','2012-2-13','WCRR','Tokyo','Motoring','Japanese', '2019-12-16 19:36:18', '2019-10-14 23:52:31', 'wordpress.com/elementum/pellentesque/quisque/porta.xml',  33);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Votación de presentaciones','2020-7-20','HAB Recruiting Day','A Coruña','Technology','English','2019-11-01 02:53:04', '2020-01-25 22:40:05', 'weather.com/cursus/id/turpis.aspx',  14);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Gestión cocina','2004-1-14','Madrid Fusion','Madrid','Gastronomy','Spanish','2018-09-02 05:40:20', '2019-10-13 08:56:22', 'twitpic.com/natoque/penatibus.html', 24);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Creativity, Symbol, and Aesthetic Sense','2018-8-13','WCPhilosophy','Beijin','Social','Chinese','2019-08-25 09:10:57', '2020-02-28 23:38:47', 'who.int/nisl/nunc/rhoncus/dui/vel/sem.html', 4);
INSERT INTO presentations (title,presentation_date,presentation_event ,city ,category ,presentation_language ,date_louded_presentation ,date_modification_presentation ,video ,user_id)VALUES ('Introducing iPhone','2007-1-9','Macworld','San Francisco','Technology','English','2017-11-20 21:41:13', '2019-11-28 23:19:32', 'techcrunch.com/vestibulum/velit/id/pretium/iaculis/diam.aspx', 50);
